version: '3.7'

services:
  adobe_media_server:
    build: ./docker/
    container_name: adobe_media_server
    ports:
      - 1935:1935
      - 1111:1111
      - 8080:80
    volumes:
      - adobe_media_server:/opt/adobe/ams
      - ./applications:/opt/adobe/ams/applications

volumes:
  adobe_media_server:
