version: '3.7'

services:
  ams:
    image: flexconstructor/docker-adobe-media-server
    container_name: ams
    ports:
      - 1935:1935
      - 1111:1111
      - 8080:80
    volumes:
      - amsdata:/opt/adobe/ams
      - ./applications:/opt/adobe/ams/applications
      - ./conf:/opt/adobe/ams/conf

volumes:
  amsdata:
